### ISSUE TITLE
request timed out

### ISSUE THREAD

**Issue by ralyodio** [alephjs/esm.sh#215]
```
error: Import 'https://cdn.esm.sh/v57/nlcst-to-string@2.0.4/es2021/nlcst-to-string.js' failed: 408 Request Timeout
    at https://cdn.esm.sh/v57/parse-latin@5.0.0/es2021/parse-latin.js:2:27264
```

```
import { retext } from 'https://cdn.esm.sh/v57/retext@8.1.0/es2021/retext.js';
import retextKeywords from 'https://cdn.esm.sh/v57/retext-keywords@7.1.0/es2021/retext-keywords.js';
import retextPos from 'https://cdn.esm.sh/v57/retext-pos@4.1.0/es2021/retext-pos.js';
```

**Comment by talentlessguy** [comment]
is this bug still present?

**Comment by samlaycock** [comment]
I'm getting the same trying to import `@aws-sdk/client-kinesis`:

```
import * as Kinesis from "https://esm.sh/@aws-sdk/client-kinesis@3.41.0?pin=v57&no-check";
```

```
Download https://cdn.esm.sh/v57/@aws-crypto/crc32@2.0.0/deno/crc32.js
Check file:///Users/samuellaycock/Development/Open%20Source/deno-hotwired/lib/event/deps.ts
error: Import 'https://cdn.esm.sh/v57/@aws-crypto/crc32@2.0.0/deno/crc32.js' failed: 408 Request Timeout
```

Had it with other `@aws-sdk` packages, but they eventually worked after waiting a while. This has been like this since I originally tried to download it 2 days ago...

**Comment by jacque006** [comment]
I'm also encountering this. Seems to fail for some packages but works for others.

#### HTTP 408
- https://esm.sh/bls-wallet-clients@0.2.2
- https://esm.sh/bls-wallet-clients@0.3.0-rc.3
- https://esm.sh/bls-wallet-clients
- https://esm.sh/rascal

#### Works fine
- https://esm.sh/react
- https://esm.sh/ethers
- https://esm.sh/ethers@5.5.1

Looks like some more heavily used/common packages that are already cached are okay.

#### Workaround

Use https://cdn.skypack.dev or another similar esm shim provider/cdn.

- https://cdn.skypack.dev/bls-wallet-clients
- https://cdn.skypack.dev/bls-wallet-clients@v0.3.0-rc.3

**Comment by deckchairlabs** [comment]
Had this output presented to me, after I received a 408 previously. Looks like the CDN has cached the output of the process even though it failed to process the request.

You should be able to see the same output by visiting https://esm.sh/react-router-dom/server

<pre>
yarn add react-router-dom@6.0.2: yarn add v1.22.11
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > react-router-dom@6.0.2" has unmet peer dependency "react@>=16.8".
warning " > react-router-dom@6.0.2" has unmet peer dependency "react-dom@>=16.8".
warning "react-router-dom > react-router@6.0.2" has unmet peer dependency "react@>=16.8".
error Could not write file "/tmp/esm-build-92694869e2404d4459722e05644d3c3e93d6fb6e-4812977b/yarn-error.log": "ENOSPC: no space left on device, open '/tmp/esm-build-92694869e2404d4459722e05644d3c3e93d6fb6e-4812977b/yarn-error.log'"
error An unexpected error occurred: "ENOSPC: no space left on device, mkdir '/tmp/esm-build-92694869e2404d4459722e05644d3c3e93d6fb6e-4812977b/node_modules/react-router'".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
</pre>

**Comment by ije** [comment]
I just released **v58**, fixed the build cache problem (build task did not delete the cache directory after build randomly that stolen a lot system space).

**Comment by jacque006** [comment]
Confirmed that issue is resolved/fixed on my end, thanks @ije !

**Comment by samlaycock** [comment]
@ije thanks for the update, but I'm still having problems importing into Deno. It seems that `/es2021` builds are fine, but the `/deno` ones still seem to time out.

I can run this project locally and it appears to work fine using `localhost:8080`, it's only when downloading from `https://esm.sh` that the timeouts happen.

**Comment by ije** [comment]
@samlaycock which package you import? i will look into it

**Comment by DetachHead** [comment]
@ije getting 408 trying to use any of my packages, eg. https://esm.sh/@detachhead/ts-helpers

**Comment by SeparateRecords** [comment]
I'm getting timeouts with the lastest AJV versions (8.6.3 works for me but it might be cached, 8.7.0+ is broken)
https://esm.sh/ajv@8.8.2/dist/jtd

**Comment by ije** [comment]
@SeparateRecords I just recovered the stable queue used before in https://github.com/alephjs/esm.sh/pull/218/commits/c2677efdcd58586fc9c8d794056ba52e7fd02ab6

**Comment by samlaycock** [comment]
@ije Hey, sorry for the delayed response. My issue was around some dependencies related to `@aws-sdk/*` packages, but it appears this is now fixed with the latest changes. Thanks!

**Comment by myobie** [comment]
I'm seeing timeouts for `preact/debug` and `preact/test-utils`. `preact` and `preact/hooks` are working. I've tried to pin back a couple versions, but they timeout as well.

**Comment by johanbrook** [comment]
As of today, with esm.sh v58, I'm also seeing timeouts for https://esm.sh/preact@10.

**Comment by johanbrook** [comment]
Now it works again, but I briefly saw this while refreshing:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "yarn add preact@10.6.1: yarn add v1.22.17\ninfo No lockfile found.\n[1/4] Resolving packages...\n[2/4] Fetching packages...\n[3/4] Linking dependencies...\nerror An unexpected error occurred: \"ENOENT: no such file or directory, copyfile '/esms/yarn/v6/npm-preact-10.6.1-e14de611b65aea5e656249d19582c457fb0aa255-integrity/node_modules/preact/README.md' -\u003e '/tmp/esm-build-1c052b647e58939025a8add6a7b5c259e7bded07-f613e5bd/node_modules/preact/README.md'\".\ninfo If you think this is a bug, please open a bug report with the information provided in \"/tmp/esm-build-1c052b647e58939025a8add6a7b5c259e7bded07-f613e5bd/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n");
export default null;
```

**Comment by myobie** [comment]
Just FYI – I've setup a copy of `esm.sh` to run in my infra and it is able to build and serve all the packages I am using without any timeouts, so I do think the production builds of some packages are stuck in some way I don't understand. Also, thanks for making it so easy to boot up and host ❤️

**Comment by ije** [comment]
i improved the nodejs service in https://github.com/alephjs/esm.sh/pull/218/commits/65f0b94172e3dbd1e5900bbc3f5b701013f5eac0, which may block the message channel then case the timeout problem

**Comment by myobie** [comment]
So far, every package I've tested on esm.sh has worked, so your fix may have indeed fixed the timeouts. I'll keep checking for the next few days and let you know if I see anymore.

**Comment by nnmrts** [comment]
Yup, this fixed everything, thanks @ije. For example, `react@18` just didn't work before, now it does without any problems.
